import * as vscode from 'vscode';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { CoreClient, bundledExecutable } from '../core';
import * as p from '../protocol';
import type { activate } from '../extension';
export async function run(): Promise<void> {
    const root=process.env.CODEMORI_TEST_PROJECT!, store=process.env.CODEMORI_TEST_DATA_DIR!;
    const extension=vscode.extensions.getExtension('lusyne.codemori')!;
    const api=await extension.activate() as Exclude<ReturnType<typeof activate>,undefined>;
    const client=new CoreClient(bundledExecutable(extension.extensionPath),store);
    await fs.mkdir(path.join(root,'pay'),{recursive:true});
    const file=path.join(root,'pay/service.ts'); await fs.writeFile(file,'function pay() {\n  return 42;\n}\n');
    const document=await vscode.workspace.openTextDocument(file);await vscode.window.showTextDocument(document,vscode.ViewColumn.One);
    await vscode.commands.executeCommand('codemori.open'); await api.waitForRender();
    await vscode.commands.executeCommand('codemori.associateDocument'); const draft=api.draft();assert.ok(draft?.binding);
    const response=await api.request({id:'context-save',action:'save',token:draft.token,scope:'personal',bindingKind:'module',input:{...draft.input,title:'Payment module',url:'https://example.com/pay'}});assert.equal(response?.ok,true,response?.error);
    const w=p.workspace(await client.call({op:'workspace_register',root}));
    const read=async()=>p.object(await client.call({op:'library_file_documents',root,workspace_id:w.id,path:'pay/service.ts'}));
    let data=await read();let entry=p.association(p.array(data.entries,v=>v)[0]);assert.equal(entry.binding.path,'pay');assert.equal(entry.inherited,true);assert.equal(entry.review_state.status,'current');
    const lenses=async()=>await vscode.commands.executeCommand<vscode.CodeLens[]>('vscode.executeCodeLensProvider',document.uri) || [];
    const wait=async(check:()=>Promise<boolean>)=>{const until=Date.now()+15000;while(Date.now()<until){if(await check())return;await new Promise(r=>setTimeout(r,100));}throw new Error('Context hint condition timed out');};
    await wait(async()=> (await lenses()).some(l=>l.command?.title.includes('1 篇文档')));
    const config=vscode.workspace.getConfiguration('codemori',document.uri);await config.update('documentHints.enabled',false,vscode.ConfigurationTarget.Workspace);
    await wait(async()=> !(await lenses()).some(l=>l.command?.command==='codemori.open'));assert.equal(p.array((await read()).records,p.record).length,1);
    await vscode.commands.executeCommand('codemori.toggleHints');await wait(async()=> (await lenses()).some(l=>l.command?.command==='codemori.open'));
    const links=p.object(await client.call({op:'code_link_create',root,path:'pay/service.ts',line:2}));
    const edit=new vscode.WorkspaceEdit();edit.insert(document.uri,new vscode.Position(0,0),'// inserted header\n');await vscode.workspace.applyEdit(edit);await document.save();
    await wait(async()=> (await lenses()).some(l=>l.command?.title.includes('待复核')));
    await api.receiveCodeLink(p.string(links.vscode_url));assert.equal(vscode.window.activeTextEditor?.selection.start.line,2);
    entry=p.association(p.array((await read()).entries,v=>v)[0]);
    await client.call({op:'binding_review',binding:entry.binding,fingerprint:entry.review_state.fingerprint,document_revision:entry.record.revision});
    assert.equal(p.association(p.array((await read()).entries,v=>v)[0]).review_state.status,'current');
    await vscode.commands.executeCommand('workbench.action.closeActiveEditor');await fs.rename(path.join(root,'pay'),path.join(root,'billing'));
    const preview=p.object(await client.call({op:'paths_repair',workspace_id:w.id,from:'pay',to:'billing'}));assert.equal(preview.bindings,1);
    await client.call({op:'paths_repair',workspace_id:w.id,from:'pay',to:'billing',token:preview.token});
    const moved=p.object(await client.call({op:'library_file_documents',root,workspace_id:w.id,path:'billing/service.ts'}));assert.equal(p.array(moved.records,p.record).length,1);
    await api.receiveCodeLink(p.string(links.vscode_url));assert.equal(vscode.window.activeTextEditor?.document.uri.fsPath,path.join(root,'billing/service.ts'));
    const second=p.record(await client.call({op:'record_create',record:{kind:'document',title:'Second design',url:'https://example.com/second'}}));
    await client.call({op:'document_link',binding:{workspace_id:w.id,path:'billing/service.ts',document_id:second.id}});
    await fs.writeFile(path.join(root,'billing/service.ts'),'// formatted again\nfunction pay() { return 42; }\n');
    const observed=await api.request({id:'batch-view',action:'search',filter:{query:''},reloadTags:true});assert.equal(observed?.ok,true);
    const oldView=p.object(observed.data);assert.equal(p.array(oldView.associations,p.association).filter(e=>e.review_state.status==='needs_review').length,2);
    await fs.writeFile(path.join(root,'billing/service.ts'),'// another change\nfunction pay() { return 42; }\n');
    const stale=await api.request({id:'batch-stale',action:'reviewCurrent',token:oldView.reviewToken});assert.equal(stale?.ok,true);assert.equal(p.object(stale.data).confirmed,0);assert.ok(p.array(p.object(stale.data).errors,p.string).length>0);
    const fresh=await api.request({id:'batch-fresh',action:'search',filter:{query:''},reloadTags:true});assert.equal(fresh?.ok,true);
    const confirmed=await api.request({id:'batch-confirm',action:'reviewCurrent',token:p.object(fresh.data).reviewToken});assert.equal(confirmed?.ok,true);assert.equal(p.object(confirmed.data).confirmed,2);assert.deepEqual(p.object(confirmed.data).errors,[]);
    await client.call({op:'identity_set',display_name:'Batch QA'});
    const sharedInfo=p.projectInfo(await client.call({op:'project_info',root}));assert.ok(sharedInfo);
    await client.call({op:'project_save',root,expected_version:sharedInfo.version,record:{kind:'document',title:'Shared design',url:'https://example.com/shared-batch'},binding_path:'billing/service.ts'});
    await fs.writeFile(path.join(root,'billing/service.ts'),'// mixed libraries\nfunction pay() { return 42; }\n');
    const mixed=await api.request({id:'mixed-view',action:'search',filter:{query:''},reloadTags:true});assert.equal(mixed?.ok,true);
    const sharedPath=path.join(root,'.codemori/shared.json');const manifest=JSON.parse(await fs.readFile(sharedPath,'utf8'));manifest.records[0].input.title='Changed while reviewing';await fs.writeFile(sharedPath,JSON.stringify(manifest));
    const partial=await api.request({id:'mixed-confirm',action:'reviewCurrent',token:p.object(mixed.data).reviewToken});assert.equal(partial?.ok,true);assert.equal(p.object(partial.data).confirmed,2);assert.equal(p.array(p.object(partial.data).errors,p.string).length,1);
    const remaining=await api.request({id:'mixed-fresh',action:'search',filter:{query:''},reloadTags:true});assert.equal(remaining?.ok,true);
    const sharedDone=await api.request({id:'mixed-retry',action:'reviewCurrent',token:p.object(remaining.data).reviewToken});assert.equal(sharedDone?.ok,true);assert.equal(p.object(sharedDone.data).confirmed,1);
    await fs.writeFile(path.join(process.env.CODEMORI_TEST_OUTPUT!,'batch-result.json'),JSON.stringify({oneActionConfirmed:2,staleBatchConfirmed:0,noSecondModal:true,currentFileOnly:true,partialConfirmed:2,sharedConflictReported:true,sharedRetryConfirmed:1},null,2));
    await fs.writeFile(path.join(process.env.CODEMORI_TEST_OUTPUT!,'contextual-result.json'),JSON.stringify({vscode:vscode.version,moduleSaveViaController:true,inheritedBindingOrigin:true,codeLensVisible:true,hiddenWithoutDeleting:true,toggleRestored:true,changeHint:true,reviewConfirmed:true,lineAnchorFollowed:true,movedLinkResolved:true,pathRepair:true},null,2));
    console.log('CodeMori contextual host passed');
}
